### ISSUE TITLE
Have detection model baselines been open-sourced?

### ISSUE THREAD

**Issue by sairights** [Hello-SimpleAI/chatgpt-comparison-detection#16]
Hi developers,

I'm kind of wondering whether detection model baseline codes & pretrained models (e.g. RoBERTa & GLTA) have been released; I failed find them in the repo or on the project main page... Please remind me if they have been open-sourced. Thank you very much!

**Comment by izhx** [comment]
Deep learning based text classifiers use the code of `transformers`, pretrained models' links are listed in the end of section [Hello-SimpleAI/chatgpt-comparison-detection#chatgpt-detectors](https://github.com/Hello-SimpleAI/chatgpt-comparison-detection#chatgpt-detectors--%E5%86%85%E5%AE%B9%E6%A3%80%E6%B5%8B%E5%99%A8) (a table).

**Comment by sairights** [comment]
Thank you so much!
